[package]
name = "rset"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="*"
nix="*"
lazy_static = "1.4.0"
rcommon = {path ="../common"}
[lib]
crate-type = ["staticlib","rlib"]
name = "rset"
