[package]
authors = ["huzhengming"]
name = "rcomplete"
version = "0.0.1"
##build = "../build.rs"
edition = "2018"


[dependencies]
lazy_static = "1.4.0"
libc = "0.2"
nix = "0.23.0"

[lib]
crate-type = ["cdylib"]
name = "rcomplete"
