[package]
authors = ["zhanghuanhuan"]
name = "rbreak"
version = "0.0.1"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
nix = "0.23.0"

[lib]
crate-type = ["staticlib","rlib"]
name = "rbreak"

