[package]
authors = ["huzhengming"]
name = "rcd"
version = "0.0.1"
edition = "2018"
build = "../build.rs"


[dependencies]
lazy_static = "1.4.0"
libc = "0.2"
rcommon = {path="../common"}
nix = "0.23.0"

[lib]
crate-type = ["staticlib","rlib"]
name = "rcd"
