[package]
name = "alias"
version = "0.1.0"
edition = "2018"
authors = ["liutong"]


[lib]
name = "ralias"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
rcmd = {path="../cmd"}
# nix = "0.23"
