[package]
name = "ralias"
version = "0.1.0"
edition = "2018"
authors = ["liutong"]


[lib]
name = "ralias"
crate-type = ["staticlib","rlib"]

[dependencies]
libc = "0.2"
rcmd = {path="../cmd"}
rcommon= {path="../common"}
# nix = "0.23"
rcommon = {path = "../common"}
