[package]
name = "rcommon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
nix = "0.24"
unic-langid = "0.9.0"
[lib]
crate-type = ["staticlib","rlib"]
name = "rcommon"
