[package]
name = "rsbash"
version = "0.1.0"
edition = "2021"
[lib]
name = "rsbash"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["builtins_rust/read", "builtins/command1", "builtins/command2", "builtins_rust/common"]

[dependencies]
libc = "0.2"
command1 = {path = "./builtins/command1"}
command2 = {path = "./builtins/command2"}
read = {path = "./builtins_rust/read"}
common = {path = "./builtins_rust/common"}
