[package]
name = "rsbash"
version = "0.1.0"
edition = "2021"
[lib]
name = "rsbash"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["builtins_rust/read", "builtins/command1", "builtins/command2", "builtins_rust/history", "builtins_rust/kill",
"builtins_rust/rlet", "builtins_rust/mapfile", "builtins_rust/printf", "builtins_rust/rreturn"]

[dependencies]
libc = "0.2"
command1 = {path = "./builtins/command1"}
command2 = {path = "./builtins/command2"}
read = {path = "./builtins_rust/read"}
history = {path = "./builtins_rust/history"}
kill = {path = "./builtins_rust/kill"}
rlet = {path = "./builtins_rust/rlet"}
mapfile = {path = "./builtins_rust/mapfile"}
printf = {path = "./builtins_rust/printf"}
rreturn = {path = "./builtins_rust/rreturn"}
